scripts: Fix up install-dev.sh with the master branches on Apple Sillicon (M1)
Currently grpcio wheel build is failing with the following error:

  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/openssl@1.1/include -I/opt/homebrew/opt/sqlite/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/zlib/include -I/opt/homebrew/opt/gdbm/include -I/opt/homebrew/opt/tcl-tk/include -I/opt/homebrew/opt/xz/include -I/opt/homebrew/opt/snappy/include -I/opt/homebrew/opt/libffi/include -I/opt/homebrew/opt/protobuf/include -I/Users/joongi/.pyenv/versions/3.9.1/envs/venv-dev2103-manager/include -I/Users/joongi/.pyenv/versions/3.9.1/include/python3.9 -c /var/folders/px/kd_s8rw556q7cjf9319dx4cm0000gn/T/tmp63t09sr6/a.c -o None/var/folders/px/kd_s8rw556q7cjf9319dx4cm0000gn/T/tmp63t09sr6/a.o
  Traceback (most recent call last):
    File "/Users/joongi/.pyenv/versions/3.9.1/lib/python3.9/distutils/unixccompiler.py", line 117, in _compile
      self.spawn(compiler_so + cc_args + [src, '-o', obj] +
    File "/private/var/folders/px/kd_s8rw556q7cjf9319dx4cm0000gn/T/pip-install-4s9i676l/grpcio_26532219a1804455b25f15ccf6cf3ab3/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
      _classic_spawn(self, command)
    File "/Users/joongi/.pyenv/versions/3.9.1/lib/python3.9/distutils/ccompiler.py", line 910, in spawn
      spawn(cmd, dry_run=self.dry_run)
    File "/Users/joongi/.pyenv/versions/3.9.1/lib/python3.9/distutils/spawn.py", line 87, in spawn
      raise DistutilsExecError(
  distutils.errors.DistutilsExecError: command '/usr/bin/clang' failed with exit code 1